### ISSUE TITLE
Wrong Cron Job Configuration

### ISSUE THREAD

**Issue by ridvanaltun** [davidjameshowell/epcigames-freegames-heroku#1]
`EpicGamesFreeGamesRun` is misconfigured and runs 2-3 times in every hour.

`* 0-23 * * *` -> Runs every minute (in `EpicGamesFreeGamesRun`)

`0 0-23 * * *` -> Runs every hour, on the hour (it should be)

There is no need to run a dyno every hour, for me it is waste of free dyno hours.

I think this definition more sense:

`0 */4 * * *` -> Runs on the 0, 4, 8, 12, 16 and 20th hour (runs 6 times in a day)

I didn't create a PR because I don't know which settings you will prefer.

**Comment by davidjameshowell** [comment]
Good call; I think 6 times a day, is more than enough. We'll switch to that; I didn't really validate the cron when I did that.

**Comment by davidjameshowell** [comment]
Resolved. Thanks for taking a look!
