### ISSUE TITLE
Claim only 1 time

### ISSUE THREAD

**Issue by octavegraf** [davidjameshowell/epcigames-freegames-heroku#13]

**Comment by chaoscreater** [comment]
having the same issue as well. I've updated to the latest build, reset my cookies and it claimed the game OK.

However, today there was supposed to be a new freebie that it is supposed to claim and it didn't. I got the captcha email and when I tried to verify, it shows this error message:

"Could not find captcha id...."

**Comment by Nwaraude** [comment]
> having the same issue as well. I've updated to the latest build, reset my cookies and it claimed the game OK.
> 
> 
> 
> However, today there was supposed to be a new freebie that it is supposed to claim and it didn't. I got the captcha email and when I tried to verify, it shows this error message:
> 
> 
> 
> "Could not find captcha id...."

What are theses captchas i never received once, only when i activated the system

**Comment by Nwaraude** [comment]
Ok finally, Maildrop sent like 50 mails with the captcha to confirm. I confirmed it two-three times and it worked well. Thank you.
