### ISSUE TITLE
Clarification: How do I update the app?

### ISSUE THREAD

**Issue by drkui** [davidjameshowell/epcigames-freegames-heroku#7]
Under the Update section, I'm a bit confused by this part: "Running the workflow manually via Github Actions".

I'm assuming its running the EpicGamesFreeGamesUpdate workflow manually. Or perhaps one of the other three workflows?

**Comment by davidjameshowell** [comment]
That is correct. You can either run it manually via Github Actions (run workflow and select main branch) or via any pushes to main. The Update named workflow essentially does a rebuild.

**Comment by drkui** [comment]
Thanks for the clarification!
